/*
 * generated by Xtext
 */
package org.xtext.workshop;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WebGuiRuntimeModule extends org.xtext.workshop.AbstractWebGuiRuntimeModule {

}
