/*
* generated by Xtext
*/
package org.xtext.workshop.ui.contentassist;

import org.xtext.workshop.ui.contentassist.AbstractWebGuiProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WebGuiProposalProvider extends AbstractWebGuiProposalProvider {

}
