
/*
 * generated by Xtext
 */
 
package org.xtext.workshop.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class WebGuiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xtext.workshop.ui.internal.WebGuiActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xtext.workshop.ui.internal.WebGuiActivator.getInstance().getInjector("org.xtext.workshop.WebGui");
	}
	
}
