/*
 * generated by Xtext
 */
package org.xtext.workshop.formatting;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.util.Pair;
import org.xtext.workshop.services.WebGuiGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class WebGuiFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		
		WebGuiGrammarAccess webgui = (WebGuiGrammarAccess) getGrammarAccess();
		
		c.setAutoLinewrap(120);
		
		// generic '{' and '}' formatting
		for (Pair<Keyword, Keyword> pair : webgui.findKeywordPairs("{", "}") ) {
			c.setIndentationIncrement().after( pair.getFirst() );
			c.setIndentationDecrement().before(	pair.getSecond() );
			c.setLinewrap().after( pair.getFirst() );
			c.setLinewrap().after( pair.getSecond() );
		}
		
		// formatting for entity
		/*
		c.setIndentationIncrement().after(
				webgui.getEntityAccess().getLeftCurlyBracketKeyword_2());
		c.setIndentationDecrement().before(
				webgui.getEntityAccess().getRightCurlyBracketKeyword_4());
		c.setLinewrap().after(
				webgui.getEntityAccess().getLeftCurlyBracketKeyword_2());
		c.setLinewrap().after(
				webgui.getEntityAccess().getRightCurlyBracketKeyword_4());
		*/
		
		// formatting for feature
		c.setLinewrap().after(
				webgui.getFeatureAccess().getRule());
		c.setNoSpace().before(
				webgui.getFeatureAccess().getMultivaluedSKeyword_3_0());
		
		// formatting for data type
		c.setLinewrap().after(
				webgui.getDataTypeRule() );

		
		// formatting for page
		c.setLinewrap().after(
				webgui.getPageAccess().getTitleSTRINGTerminalRuleCall_5_0() );
		
		
		// formatting for display element
		c.setLinewrap().after(
				webgui.getDisplayElementRule() );
		
		// formatting for action element
		c.setLinewrap().after(
				webgui.getActionElementRule() );
		
		
		// formatting for comments
		c.setLinewrap(0, 1, 2).before(webgui.getSL_COMMENTRule());
		c.setLinewrap(0, 1, 2).before(webgui.getML_COMMENTRule());
		c.setLinewrap(0, 1, 1).after(webgui.getML_COMMENTRule());
	}
}
